name: contacts
description: A new Flutter project.



publish_to: "none" 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  cupertino_icons: ^0.1.3
  sqflite:
  path:
  url_launcher: ^5.4.2
  local_auth: 0.6.1+3
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  uuid: ^2.0.4
  image_crop: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/profile-picture.png
  

  
  

  
  

  
  
  
  
  
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
